version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5433:5432"  # Map port 5433 on the host to 5432 in the container
    environment:
      POSTGRES_USER: postgres  # Username for PostgreSQL
      POSTGRES_PASSWORD: postgres  # Password for PostgreSQL
      POSTGRES_DB: loan_service_db  # Initial database to create
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data on host

volumes:
  postgres_data:
